package shiprocket

var SHIPROCKET_BUCKETS = []string{"Pickups", "In Transit", "Delivered", "RTO", "Returns"}

var SHIPROCKET_STATUSES = []string{"NEW", "READY TO SHIP", "OUT FOR PICKUP", "PICKUP SCHEDULED", "PICKED UP", "CANCELED", "PICKUP EXCEPTION", "PICKUP ERROR", "OUT FOR DELIVERY", "IN TRANSIT", "REACHED AT DESTINATION HUB", "SHIPPED", "DELIVERED", "RETURN OUT FOR DELIVERY", "RETURN OUT FOR PICKUP", "RTO DELIVERED", "RTO IN TRANSIT", "RTO INITIATED", "RTO_OFD", "UNDELIVERED", "CANCELED", "RETURN DELIVERED"}

// var SHIPROCKET_STATUSES = []string{}

var SHIPROCKET_ORDER_TRACKING_BUCKET = map[string][]string{
	"Pickups":      {"NEW", "READY TO SHIP", "OUT FOR PICKUP", "PICKUP SCHEDULED", "PICKED UP", "CANCELED", "PICKUP EXCEPTION", "PICKUP ERROR"},
	"In Transit":   {"SHIPPED", "OUT FOR DELIVERY", "IN TRANSIT", "REACHED AT DESTINATION HUB"},
	"Delivered":    {"DELIVERED"},
	"RTO":          {"RETURN OUT FOR DELIVERY", "RETURN OUT FOR PICKUP", "RTO DELIVERED", "RTO IN TRANSIT", "RTO INITIATED", "RTO_OFD"},
	"Returns":      {"UNDELIVERED", "CANCELED", "RETURN DELIVERED"},
	"Pickup Error": {"PICKUP EXCEPTION", "PICKUP ERROR"},
}
