package whatsapp

var WHATSAPP_BASE_URL string
var WHATSAPP_ACCESS_TOKEN string
var WHATSAPP_PHONE_NUMBER_ID string

var WHATSAPP_SERVICE_BASE_URL string
var WHATSAPP_SERVICE_API_KEY string

var WHATSAPP_ORDER_CONFIRMATION_TEMPLATE_ID string
var WHATSAPP_ORDER_DELIVERED_TEMPLATE_ID string
var WHATSAPP_ORDER_OFD_TEMPLATE_ID string
var WHATSAPP_ORDER_SHIPPED_TEMPLATE_ID string
var WHATSAPP_ACR_20MINS_TEMPLATE_ID string
var WHATSAPP_ACR_4HRS_TEMPLATE_ID string
var WHATSAPP_ACR_24HRS_TEMPLATE_ID string
var WHATSAPP_ACR_3DAYS_TEMPLATE_ID string
var WHATSAPP_PAYMENT_LINK_TEMPLATE_ID string
var WHATSAPP_COD_CONFIRM string
var WHATSAPP_REVIEW_TEMPLATE_ID string
var WHATSAPP_NDR_TEMPLATE_ID string
var WHATSAPP_REORDER_TEMPLATE_ID string
var WHATSAPP_ORDER_IN_TRANSIT string
var WHATSAPP_ORDER_OUT_FOR_PICKUP_TEMPLATE_ID string
var WHATSAPP_ORDER_PICKEDUP_TEMPLATE_ID string
var WHATSAPP_JOINAMBASSDOR_TEMPLATE_ID string
var WHATSAPP_AMBASSOR_ONBOARDING_TEMPLATE string
var WHATSAPP_INFLUENCER_ONBOARDING_TEMPLATE string
var WHATSAPP_INFLUENCER_APPROVAL_TEMPLATE string
var WHATSAPP_INFLUENCER_DISAPPROVAL_TEMPLATE string
var WHATSAPP_AMBASSADOR_DEAL string

type commType int

const (
	Unknown commType = iota
	POSTTRANSACTIONCOMM
	MARKETTINGCOMM
	ORDERCOMM
	Login
	FromUser
	Chat
	REVIEW
	REORDER
	SHIPMENT
	RECRUITMENT
	DEAL
	INFLUENCER
)

type quickReplyBut int

const (
	ReviewBut quickReplyBut = iota
	ReOrderBut
	NDR_BUTTON
	RECOVERCARTBUT
	AMBASSDORJOIN
	CODCONFIRM
)
